#!/usr/bin/php


<?php

$_SERVER['DOCUMENT_ROOT'] = __DIR__."/public/";

require('vendor/discophp/framework/core/Disco.core.php');

function errorHandler($errNo,$errStr,$errFile,$errLine){
    switch($errNo){
        case E_USER_ERROR:
            $f = $errNo.' '.$errStr.' '.$errFile.' '.$errLine;
            shell_exec('echo "'.$f.'" > ../logs/disco-jobs.log');
            exit(1);
            break;
    }//switch
    return true;
}//errorHandler


set_error_handler("errorHandler");


if(isset($argv[1])){

    switch($argv[1]){

        case 'resolve':
            Disco\manage\Manager::resolve($argv[2],$argv[3],$argv[4],$argv[5],$argv[6]);
            break;

        case 'post-install-cmd':
            Disco\manage\Manager::install();
            break;

        case 'post-update-cmd':
            echo 'Generating autoload files for Disco Addons ...';
            Disco\manage\Manager::addonAutoloads();
            echo ' done.'.PHP_EOL;
            break;

        case 'jobs':
            Disco\manage\Manager::jobs();
            break;

        case 'kill-job':
            Queue::killJob($argv[2]);
            break;

        case 'gen':
            if($argv[2]=='aes'){
                $r = Disco\manage\Manager::genAES256Key();
                if(isset($argv[3]) && $argv[3]=='set'){
                    Disco\manage\Manager::setAES256Key($r);
                    echo 'AES_KEY256 now set to : '.$r.PHP_EOL;
                }//if
                else {
                    echo $r.PHP_EOL;
                }//el
            }//if
            else if($argv[2]=='sha'){
                if(empty($argv[3])){
                    echo 'You must specify a length for the SHA512 salt'.PHP_EOL;
                    exit;
                }//if

                $s = Disco\manage\Manager::genSalt($argv[3]);

                if(!empty($argv[4]) && $argv[4]=='set-lead'){
                    Disco\manage\Manager::setSaltLead($s);
                    echo 'SHA512_SALT_LEAD now set to : '.$s.PHP_EOL;
                }//if
                else if(!empty($argv[4]) && $argv[4]=='set-tail'){
                    Disco\manage\Manager::setSaltTail($s);
                    echo 'SHA512_SALT_TAIL now set to : '.$s.PHP_EOL;
                }//if
                else {
                    echo $s.PHP_EOL;
                }//el

            }//elif

            break;

        case 'make':
            $vars=Array();
            $i=4;
            while(!empty($argv[$i])){
                $vars[]=$argv[$i];
                $i++;
            }//while

            if(isset(Disco::$facades[$argv[2]])){
                $argv[2] = call_user_func(Disco::$facades[$argv[2]]);
            }//if
            else {
                $argv[2] = new $argv[2];
            }//el

            var_dump(Disco::handle($argv[2],$argv[3],$vars));
            break;

        case 'mysql':
            $db = call_user_func(\Disco::$facades['DB']);
            echo $db->host_info.PHP_EOL;
            echo $db->server_info.PHP_EOL;
            echo $db->stat.PHP_EOL.PHP_EOL;
            break;

        case 'mode':

            if(empty($argv[2])){
                $mode = Disco\manage\Manager::appMode();
                echo 'APP_MODE : '.$mode.PHP_EOL;
                exit;
            }//if
            else if($argv[2]!='DEV' && $argv[2]!='PROD'){
                echo 'Mode takes one of two values: DEV | PROD'.PHP_EOL.'Please supply a correct value'.PHP_EOL;
                exit;
            }//if

            Disco\manage\Manager::appMode($argv[2]);
            echo 'APP_MODE now set to: '.$argv[2].PHP_EOL;

            break;

        case 'maintanance-mode':

            if(empty($argv[2])){
                $mode = Disco\manage\Manager::maintananceMode();
                if($mode=='YES'){
                    echo 'MAINTANANCE_MODE : ON'.PHP_EOL;
                }//if
                else {
                    echo 'MAINTANANCE_MODE : OFF'.PHP_EOL;
                }//el
                exit;
            }//if
            else if($argv[2]!='YES' && $argv[2]!='NO'){
                echo 'Mode takes one of two values: YES | NO '.PHP_EOL.'Please supply a correct value'.PHP_EOL;
                exit;
            }//if

            Disco\manage\Manager::maintananceMode($argv[2]);
            echo 'MAINTANANCE_MODE now set to: '.$argv[2].PHP_EOL;
            echo 'Users will being seeing the result of the file'.PHP_EOL.' -  app/maintanance.php'.PHP_EOL;
            break;


    }//switch
}//if






?>
